### ISSUE TITLE
Fails at Xorg pre-start hook

### ISSUE THREAD

**Issue by Ingvix** [Hyper-KVM/optimus-manager#3]
**Describe the bug**
I'm not sure if it's just me doing something wrong or is there a bug. At boot there's already errors when the service tries to run and then nothing works.

**System info**
Void Linux
BSPWM with startx
Thinkpad P50
Probably stable, got it from your void-packages
No custom configurations

**Logs**
`ERROR: the latest GPU setup attempt failed at Xorg pre-start hook.`

```
[12] INFO: # Xorg pre-start hook
[12] INFO: Requested mode is: igpu
[12] INFO: Checking for GDM display servers
[223] INFO: Available modules: ['nouveau', 'nvidia', 'nvidia_drm', 'nvidia_modeset', 'nvidia_uvm']
[224] INFO: Unloading modules ['nvidia_drm', 'nvidia_modeset', 'nvidia_uvm', 'nvidia'] (if loaded)
[238] INFO: Loaded extra Xorg options (0 lines)
[238] INFO: Loaded extra Xorg options (0 lines)
[242] ERROR: Xorg pre-start setup error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/optimus_manager/hooks/pre_xorg_start.py", line 34, in main
    configure_xorg(config, requested_mode)
  File "/usr/lib/python3.8/site-packages/optimus_manager/xorg.py", line 23, in configure_xorg
    xorg_conf_text = _generate_igpu(config, bus_ids, xorg_extra, igpu)
  File "/usr/lib/python3.8/site-packages/optimus_manager/xorg.py", line 152, in _generate_igpu
    text = _make_intel_device_section(config, bus_ids, xorg_extra, igpu)
  File "/usr/lib/python3.8/site-packages/optimus_manager/xorg.py", line 253, in _make_intel_device_section
    text += "\tDriver \"%s\"\n" % driver
UnboundLocalError: local variable 'driver' referenced before assignment
[250] INFO: Removing /etc/X11/xorg.conf.d/10-optimus-manager.conf (if present)
[251] INFO: Writing state {'type': 'pre_xorg_start_failed', 'switch_id': '20200611T012847', 'requested_mode': 'igpu'}
```

**Comment by Ann1kaB** [comment]
Hi sorry for the late response, I pushed a new version to my void-packages repo that should fix this, let me know if anything else isn't working thank you!

**Comment by Ingvix** [comment]
Sorry for the late response as well. I was in content running only Nvidia GPU for some time but now I'm in a need of way to easily switch between configurations again. The updated version works as it should though I'm not sure how would I make my setup run prime-switch as root after X Server stops. I'm using startx to start my X session. Do you have any idea on that?

I assume prime-switch only changes the xorg configuration and trusts the display manager or user to start the session again so it doesn't actually try to restart it itself? So would I be okay by allowing to run prime-switch as root without asking for password and aliasing `startx` to `startx; sudo prime-switch`?

**Comment by Ingvix** [comment]
Oh, right. I still better close this issue since it's solved.
