### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by 33KK** [Hyper-KVM/optimus-manager#4]
**Describe the bug**
Package for void linux has missing dependencies:
- python3-psutil
- glxinfo
- python3-setuptools seems to be required at runtime

**System info**
- Void linux

**Logs**
❯ sudo xbps-remove python3-setuptools -y > /dev/null
❯ optimus-manager --status
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
❯ sudo xbps-install python3-setuptools -y > /dev/null
❯ optimus-manager --status

Optimus Manager (Client) version 1.3.5

Current GPU mode : nvidia
GPU mode requested for next login : no change
GPU at startup : igpu
Temporary config path: no
❯ sudo xbps-remove python3-psutil -y > /dev/null
❯ optimus-manager --status
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 11, in <module>
    load_entry_point('optimus-manager==1.3.5', 'console_scripts', 'optimus-manager')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2861, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2461, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2467, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/__init__.py", line 8, in <module>
    from .. import checks
  File "/usr/lib/python3.8/site-packages/optimus_manager/checks.py", line 2, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
❯ sudo xbps-install python3-psutil -y > /dev/null
❯ optimus-manager --status

Optimus Manager (Client) version 1.3.5

Current GPU mode : nvidia
GPU mode requested for next login : no change
GPU at startup : igpu
Temporary config path: no
❯ sudo xbps-remove glxinfo -y > /dev/null
❯ optimus-manager --status
ERROR: cannot check the active card (should be "nvidia"). Reason: Cannot run glxinfo : Failed to execute '__NV_PRIME_RENDER_OFFLOAD=0 glxinfo' :
bash: glxinfo: команду не знайдено

Something went wrong during the last GPU setup...
Log at /var/log/optimus-manager/switch/switch-20200724T225540.log

Cannot execute command because of previous errors.

❯ sudo xbps-install glxinfo -y > /dev/null
❯ optimus-manager --status

Optimus Manager (Client) version 1.3.5

Current GPU mode : nvidia
GPU mode requested for next login : no change
GPU at startup : igpu
Temporary config path: no

**Comment by Ann1kaB** [comment]
Thanks, added missing dependencies.
