### ISSUE TITLE
Xorg pre-start hook did not run

### ISSUE THREAD

**Issue by ghost** [Hyper-KVM/optimus-manager#5]
So, i have similar error of #3, but something other...
**System info**
Void Linux
KDE Plasma with SDDM
Toshiba Satellite P50-C-13X
Last Version from you Void-Packages
No any custom configurations
### _I Requested switch to nvidia_
**Console output**:
`ERROR: a GPU setup was initiated but Xorg pre-start hook did not run.
Traceback (most recent call last):
  File "/usr/bin/optimus-manager", line 33, in <module>
    sys.exit(load_entry_point('optimus-manager==1.3.5', 'console_scripts', 'optimus-manager')())
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/__init__.py", line 26, in main
    fatal = report_errors(state)
  File "/usr/lib/python3.8/site-packages/optimus_manager/client/error_reporting.py", line 20, in report_errors
    print("Log at %s/switch/switch-%s.log" % (envs.LOG_DIR_PATH, state["switch_id"]))
KeyError: 'switch_id'`

And i have empty /var/log/optimus-manager/switch/ 
If i'm doing some wrong, please indicate my error (:
P.S I'm tested on Artix Runit and have the same error...

**Comment by ghost** [comment]
So, i'm sorry, i found a similar issue on main repository...
